### ISSUE TITLE
期間指定パラメータをtbs=qdr:yに変更したい

### ISSUE THREAD

**Issue by shimoju** [amazedkoumei/chrome-ext-ato-ichinen#10]
アクティブ時に付加する期間指定パラメータをtbs=qdr:yに変更したい。

現行のas_qdrパラメータを使うと黒いトップバーの旧UIになってしまうので、
新UIが行き渡った現在ではtbsパラメータに変更したほうが良いと思います。
新UI<->旧UIの遷移がなくなるため、切替速度も多少速くなることが期待できます。

**Comment by amazedkoumei** [comment]
PR ありがとうございました
